image: node:8-alpine

stages:  
  - release

release:
  stage: release
  image: docker:latest
  environment:
    name: production
    url: http://panel.davinciescape.com
  only:
    - master
  when: on_success
  services:
    - docker:dind
  before_script:
    - apk update
    - apk add openssh
    - "docker login -u dv-docker-deploy -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build \
        -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/production:latest \
        -f ./Dockerfile \
        --build-arg MONGODB_URI=${MONGODB_URI} \
        ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/production:latest"
  after_script:
    - "docker logout ${CI_REGISTRY}"
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
    - chmod 700 "${HOME}/.ssh/id_rsa"
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ${HOME}/.ssh/config
    - ssh -i "${HOME}/.ssh/id_rsa" ${DEPLOYMENT_SERVER} "sudo /srv/deploy/davinci-production.sh"
